[package]
name = "battery_saver"
version = "0.1.0"
authors = ["arpho"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
battery = "0.7.8"
uom = "0.31.0"
io_bluetooth = "0.1"
structopt = "0.3.13"
